export default [
    {
        id: 0,
        title: 'VIRTUe test building deadline',
        allDay: true,
        start: new Date(2018, 5, 2),
        end: new Date(2018, 5, 3),
    },
    {
        id: 1,
        title: 'All day Demo Day',
        allDay: true,
        start: new Date(2018, 5, 8),
        end: new Date(2018, 5, 9),
    },
    {
        id: 2,
        title: 'VIRTUe help at building site',
        start: new Date(2018, 5, 0),
        end: new Date(2018, 5, 1),
    },
    {
        id: 3,
        title: 'Demo Day setup',
        allDay: true,
        start: new Date(2018, 5, 6),
        end: new Date(2018, 5, 6),
        // start: new Date(new Date().setHours(new Date().getHours() - 3)),
        // end: new Date(new Date().setHours(new Date().getHours() + 3)),
    },
    {
        id: 4,
        title: 'Report deadline',
        allDay: true,
        start: new Date(2018, 5, 14, 17, 0, 0, 0),
        end: new Date(2018, 5, 14, 18, 0, 0, 0),
    },
    {
        id: 5,
        title: 'Portfolio deadline',
        allDay: true,
        start: new Date(2018, 5, 21, 17, 0, 0, 0),
        end: new Date(2018, 5, 21, 18, 0, 0, 0),
    },
    {
        id: 6,
        title: 'Exam',
        start: new Date(2018, 5, 29, 9, 0, 0, 0),
        end: new Date(2018, 5, 29, 12, 0, 0, 0),
    },
]